FROM fnndsc/ubuntu-python3
COPY requirements.txt ./
RUN python3 -m pip install -r requirements.txt pytest==4.3.0
WORKDIR /root/
COPY flappy ./flappy
COPY tests ./tests
ENTRYPOINT ["pytest", "-v", "tests"]