name: CI
on: [push]
jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Image
      run: docker build -f Dockerfile-lint -t flappy-bird .
    - name: Validate
      run: docker run flappy-bird
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: docker build -f Dockerfile-tests -t flappy-bird-tests .
      - name: Run tests
        run: docker run flappy-bird-tests
